import {
  Bug,
  ContactRound,
  FileText,
  GitBranch,
  HardDrive,
  Layers,
  ListTodo,
  MessageSquareText,
  Shapes,
} from "lucide-react";
export const MCP_SERVER_PRESETS = [
  {
    id: "attio",
    label: "Attio",
    url: "https://mcp.attio.com/mcp",
    protocol: "stateful",
    authType: "oauth",
    setup: "One-click OAuth",
    icon: ContactRound,
  },
  {
    id: "slack",
    label: "Slack",
    url: "https://mcp.slack.com/mcp",
    protocol: "stateful",
    authType: "oauth",
    setup: "OAuth app required",
    icon: MessageSquareText,
  },
  {
    id: "notion",
    label: "Notion",
    url: "https://mcp.notion.com/mcp",
    protocol: "stateless",
    authType: "oauth",
    setup: "One-click OAuth",
    icon: FileText,
  },
  {
    id: "github",
    label: "GitHub",
    url: "https://api.githubcopilot.com/mcp/x/all",
    protocol: "stateful",
    authType: "bearer",
    setup: "All toolsets · personal token",
    icon: GitBranch,
  },
  {
    id: "google-drive",
    label: "Google Drive",
    url: "https://drivemcp.googleapis.com/mcp/v1",
    protocol: "stateless",
    authType: "oauth",
    setup: "OAuth app required",
    icon: HardDrive,
  },
  {
    id: "linear",
    label: "Linear",
    url: "https://mcp.linear.app/mcp",
    protocol: "stateful",
    authType: "oauth",
    setup: "One-click OAuth",
    icon: ListTodo,
  },
  {
    id: "figma",
    label: "Figma",
    url: "https://mcp.figma.com/mcp",
    protocol: "stateful",
    authType: "oauth",
    setup: "One-click OAuth",
    icon: Shapes,
  },
  {
    id: "atlassian",
    label: "Atlassian",
    url: "https://mcp.atlassian.com/v2/mcp",
    protocol: "stateful",
    authType: "oauth",
    setup: "One-click OAuth",
    icon: Layers,
  },
  {
    id: "sentry",
    label: "Sentry",
    url: "https://mcp.sentry.dev/mcp",
    protocol: "stateful",
    authType: "oauth",
    setup: "One-click OAuth",
    icon: Bug,
  },
] as const;
